# This workflow builds a xar archive, deploys it into exist and execute a simple smoke test.
# It also includes code for using semantic-release to upload packages as part of GitHub releases
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
# For node free automated release see https://trstringer.com/github-actions-create-release-upload-artifacts/ 

name: exist-db CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
       fail-fast: false
       matrix:
        # 7.0.0-SNAPSHOT and 6.2.0
         exist-version: [6.2.0, latest]
         java-version: [11, 17]
         exclude:
           - exist-version: 6.2.0
             java-version: 17
           - exist-version: latest
             java-version: 11

    steps:
      # Checkout code
      - uses: actions/checkout@v4
      - name: Install OS Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libxml2-utils bats

      - name: Install Python Dependencies
        run: pip install lxml
          
      # sanity check
      - name: Ensure all XML Files are Well-formed
        run: |
          xmllint --noout \
            $(find . -type f -name '*.xml')

      # Run Python script to combine register files for validation
      # TODO(DP): commit this file back?
      - name: generate combined indices
        run: python documentation/scripts/create-combined-index-list.py

      - name: Validate Data Files
        run: |
          xmllint --noout --nowarning \
          --relaxng resources/odd/BEBB_schema.rng \
          data/edited_text/**/*.xml

      - name: Validate Register Files
        run: |
          xmllint --noout --nowarning \
          --xinclude --relaxng resources/odd/tei_all.rng \
          data/register/combined-indices.xml

      # Build 
      - name: Build Expath Package
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java-version }}
      - run: ant

      # Install
      - name: Pull container image
        run: docker pull duncdrum/existdb:${{ matrix.exist-version }}

      - name: Start exist-ci containers
        run: |
          docker run -dit -p 8080:8080 -v ${{ github.workspace }}/build:/exist/autodeploy \
          --name exist --rm --health-interval=2s --health-start-period=4s \
          duncdrum/existdb:${{ matrix.exist-version }}

      - name: wait for install to finish
        timeout-minutes: 10
        run: |
          while ! docker logs exist | grep -q "Server has started"; \
          do sleep 2s; \
          done      

      # Test       
      - name: Run test
        run: bats --tap test/*.bats

      # Lint commit messages when autoversioning
    #   - name: lint commit message
    #     uses: wagoid/commitlint-github-action@v6

#   release:
#     name: Release
#     runs-on: ubuntu-latest
#     needs: build
#     if: github.ref == 'refs/heads/main'
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4 
#       - name: Setup Node.js
#         uses: actions/setup-node@v4
#         with:
#           cache: npm  
#           node-version: lts/*
#       - name: Install dependencies
#         run: npm ci --no-optional   
#       - name: Perform Release
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#           PUBLIC_REPO: ${{ secrets.PUBLIC_REPO }}
#         run: npx semantic-release
        # TODO(DP): 
        #   - add secrets to github
        #   - publish to public repo?